# theme = "Chalk.dark"
[colors.bright]
black = "#505050"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#f5f5f5"
yellow = "#ddb26f"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#d0d0d0"
yellow = "#ddb26f"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Light"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[[keyboard.bindings]]
key = "Left"
mods = "Option"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Option"
chars = "\u001bf" 

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Back"
mods = "Option"
chars = "\u001b\u007f"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
key = "W"
mods = "Command"

[keyboard.bindings.command]
args = ["kill-pane"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "\\"
mods = "Command"

[keyboard.bindings.command]
args = ["split-window", "-h"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "\\" 
mods = "Option"

[keyboard.bindings.command]
args = ["split-window"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"

[keyboard.bindings.command]
args = ["next-window"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key1"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "0"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "1"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "2"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "3"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "4"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "5"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "6"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "7"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Option"

[keyboard.bindings.command]
args = ["select-window", "-t", "8"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "0"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "1"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "2"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "3"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "4"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "5"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "6"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "7"]
program = "/opt/homebrew/bin/tmux"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"

[keyboard.bindings.command]
args = ["select-pane", "-t", "8"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "None"
opacity = 0.95

[window.padding]
x = 0
y = 0
